# Generated by Django 5.1.4 on 2025-04-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_historicalmovie_created_at_movie_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-added_at'], 'verbose_name': 'Любимые фильмы', 'verbose_name_plural': 'Любимые фильмы'},
        ),
        migrations.AddField(
            model_name='favorite',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfavorite',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
